spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com/yrg/mapper/*.xml
  type-aliases-package: com.yrg.domain